### ISSUE TITLE
Ambiguous function defination.

### ISSUE THREAD

**Issue by rohit-rk** [klahnakoski/jx-sqlite#1]
In  **/jx_sqlite/__init__.py file**, the functions  
**[1.] sql_text_array_to_set(column)** at line 194    and 
**[2.]get_column(column)** at line 204 are ambiguous.
 I think both should take one more argument i.e., adding row as an argument to both functions and calling inner function must be modified with proper arguments.
@klahnakoski

**Comment by klahnakoski** [comment]
Sorry for the late reply.

The change you are suggesting is philosophical: Your suggestion would
work for the given situations shown in the code, but I expect there to
be some complicated `pull` functions, so they should stay functions that
act on `row` and return the value required.  If you want a more
complicated pull function, you can generate it with `jx_expression()`,
and it will probably come from the query expression.

**Comment by rohit-rk** [comment]
Thank you for explanation. I saw how it works.
