### ISSUE TITLE
Library update(Question)

### ISSUE THREAD

**Issue by rohit-rk** [klahnakoski/jx-sqlite#4]
New changes made in pylibrary now results in number of test case failures. Is pylibrary part of the jx-sqlite project or just a dependency? Are the modifications in it are supposed to happen while working on jx-sqlite?

**Comment by klahnakoski** [comment]
I ran the tests again, and confirmed they are working. I also confirmed is pushed the changes to master.  There are a few more tests, so you should expect 61 failures. May you send me a test that fails?

The pyLibrary will change as this project advances, but hopefully nothing this project uses. It is an unfortunate dependency. The eventual plan is to move just the dependencies from pyLibrary to a third module which jx-sqlite can use.  Feel free to make a new directory and start moving logical parts into that directory to prepare for such a module.  If you do not do it, you will see me do it.

**Comment by rohit-rk** [comment]
Alright. Will start work on that too.

**Comment by klahnakoski** [comment]
Does the error look like..

    FAILED (errors=61, skipped=14)
    Exception TypeError: Unhandled exception in thread started by <unbound method Thread._run>"Unhandled exception in thread started by 'No<unbound method Thread._run>
    neTyTraceback (most recent call last):

    p  File "C:\Python27\lib\site-packages\mo_threads\threads.py", line 224, in _run
    Traceback (most recent call last):
    e' object is not ca    e = _Except.wrap(e)
    l  File "C:\Python27\lib\site-packages\mo_logs\exceptions.py", line 75, in wrap
    la  File "C:\Python27\lib\site-packages\mo_threads\threads.py", line 224, in _run
    ble"        e = _Except.wrap(e)
    elif isinstance(e, Mapping):
      File "C:\Python27\lib\site-packages\mo_logs\exceptions.py", line 75, in wrap
     in   File "C:\Python27\lib\abc.py", line 144, in __instancecheck__
        <bound method Snowflake.__del__ of <jx_sqlite.snowflake.Snowflake object at 0x0DD068F0>>    return cls.__subclasscheck__(subtype)
     ignored
      File "C:\Python27\lib\abc.py", line 174, in __subclasscheck__
    elif isinstance(e, Mapping):

this is not a cut-and-paste error, it really is messed up.

I am guessing that since you fixed the `__del__()` it is now getting called.  Problem is it is called late, once many other objects have been removed, including the modules it uses.

I am guessing that we should remove `__del__()` and add context managers (`__enter__` and `__exit__`) or a `close()` method to deal with table destruction.

**Comment by klahnakoski** [comment]
I removed `__del__()`

**Comment by rohit-rk** [comment]
thank you for viewing this.
